apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:CURRENCY_EXCHANGE_URI: {}
    manager: kubectl-create
    operation: Update
    time: "2021-04-26T19:03:56Z"
  name: currency-conversion
  namespace: default
